package edu.rpi.cs.csci4963.u22.cheny63.project.drawAndGuess.control;

public enum GameCommand {
    PLAYERJOINEVENT,PLAYERSENTMESSAGE,PLAYERLEFTEVENT,PLAYERSCOREUPDATE,MESSAGEDATAPACK,MODELDATAPACK,DREWEVENT,NEWROUNDEVENT
}

